// Code generated by protoc-gen-go. DO NOT EDIT.
// source: greet.proto

package greet // import "."

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HiRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HiRequest) Reset()         { *m = HiRequest{} }
func (m *HiRequest) String() string { return proto.CompactTextString(m) }
func (*HiRequest) ProtoMessage()    {}
func (*HiRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_greet_155c33e904e331cf, []int{0}
}
func (m *HiRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HiRequest.Unmarshal(m, b)
}
func (m *HiRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HiRequest.Marshal(b, m, deterministic)
}
func (dst *HiRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HiRequest.Merge(dst, src)
}
func (m *HiRequest) XXX_Size() int {
	return xxx_messageInfo_HiRequest.Size(m)
}
func (m *HiRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HiRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HiRequest proto.InternalMessageInfo

func (m *HiRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type HiResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HiResponse) Reset()         { *m = HiResponse{} }
func (m *HiResponse) String() string { return proto.CompactTextString(m) }
func (*HiResponse) ProtoMessage()    {}
func (*HiResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_greet_155c33e904e331cf, []int{1}
}
func (m *HiResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HiResponse.Unmarshal(m, b)
}
func (m *HiResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HiResponse.Marshal(b, m, deterministic)
}
func (dst *HiResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HiResponse.Merge(dst, src)
}
func (m *HiResponse) XXX_Size() int {
	return xxx_messageInfo_HiResponse.Size(m)
}
func (m *HiResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HiResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HiResponse proto.InternalMessageInfo

func (m *HiResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*HiRequest)(nil), "greet.HiRequest")
	proto.RegisterType((*HiResponse)(nil), "greet.HiResponse")
}

func init() { proto.RegisterFile("greet.proto", fileDescriptor_greet_155c33e904e331cf) }

var fileDescriptor_greet_155c33e904e331cf = []byte{
	// 110 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0x2f, 0x4a, 0x4d,
	0x2d, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x73, 0x94, 0xe4, 0xb9, 0x38, 0x3d,
	0x32, 0x83, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0x84, 0xb8, 0x58, 0xf2, 0x12, 0x73, 0x53,
	0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xc0, 0x6c, 0x25, 0x35, 0x2e, 0x2e, 0x90, 0x82, 0xe2,
	0x82, 0xfc, 0xbc, 0xe2, 0x54, 0x21, 0x09, 0x2e, 0xf6, 0xdc, 0xd4, 0xe2, 0xe2, 0xc4, 0x74, 0x98,
	0x22, 0x18, 0xd7, 0x89, 0x33, 0x8a, 0x5d, 0xcf, 0x1a, 0x6c, 0x66, 0x12, 0x1b, 0xd8, 0x06, 0x63,
	0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x65, 0xc1, 0x6f, 0x05, 0x70, 0x00, 0x00, 0x00,
}
